name: My first pipeline

on: push 

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2
              build: build image
              run: docker build -t josepheric81/ciportfolio-app .
              name: list images
              run: docker images
            
              