name: My first pipeline

on: 
  push: 
    branches:
      - main  # You might want to specify the branch you are working with

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/ciportfolio-app .
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Docker username secret
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push image to registry
        run: docker push ${{secrets.DOCKER_USERNAME}}/ciportfolio-app
      - name: List Docker images
        run: docker images